spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

logging:
  level:
    com.restaurante: DEBUG
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG